### ISSUE TITLE
UI Component API Test Setup

### ISSUE THREAD

**Issue by u19012366** [COS301-MP-AboutTime/miniproject-2023#47]
Please refer to [this](https://docs.google.com/document/d/1QVxHTni2VuX7gV0rJfmaBaHOTb0Lx6xkenatrHJ7NW0/edit?usp=sharing) file for instructions on how to use this specific test

Note: if it's still in progress / Todo, the document will not be ready to be used for this specific test.

**Comment by u19012366** [comment]
There is an issue which arises when the test should be ran, here is a snippet of the problem:
```

> nx run app-profile-data-access:test

 FAIL   app-profile-data-access  libs/app/profile/data-access/src/tests/profile.api.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/ettiennevanzyl/Library/CloudStorage/OneDrive-Personal/UP 2023/COS 301/Mini-Project/miniproject-2023/node_modules/@angular/core/fesm2015/core.mjs:7
    import { Subject, Subscription, Observable, merge as merge$1 } from 'rxjs';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { Injectable } from '@angular/core';
        | ^
      2 | import { doc, docData, Firestore } from '@angular/fire/firestore';
      3 | import { Functions, httpsCallable } from '@angular/fire/functions';
      4 | import {

      at Runtime.createScriptFromCode (../../../../node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (src/profiles.api.ts:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.952 s
Ran all test suites.

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test for project app-profile-data-access (3s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
 
```

The `Here's what you can do` section has been consulted, but to no avail.
